### ISSUE TITLE
[BUG] The frontegg package requires Flask, even if you use FastAPI.

### ISSUE THREAD

**Issue by amitripshtos** [frontegg/python-sdk#26]
Hey,
Because of import issue, in order to make this package work - we must install Flask as well (while we don't need it).

That’s because the file _mixins.py which has the following import:
from flask import request
So when using frontegg package, it calls _init_.py file which imports the _mixins.py file and if flask is not installed it wil raise an exception.
You can the see the following stacktrace:
```
Traceback (most recent call last):
  File "/Users/noam/PycharmProjects/runtime/backend/main.py", line 9, in <module>
    from frontegg.fastapi import frontegg
  File "/Users/noam/PycharmProjects/venvs/runtime/lib/python3.8/site-packages/frontegg/__init__.py", line 2, in <module>
    from frontegg.client import FronteggRESTClient, FronteggClient, FronteggContext
  File "/Users/noam/PycharmProjects/venvs/runtime/lib/python3.8/site-packages/frontegg/client.py", line 10, in <module>
    from frontegg._mixins import AuditsClientMixin, SSOClientMixin
  File "/Users/noam/PycharmProjects/venvs/runtime/lib/python3.8/site-packages/frontegg/_mixins.py", line 5, in <module>
    from flask import request
ModuleNotFoundError: No module named 'flask'
```
The solution is only use the “flask” package under the “flask” folder, and don’t call the flask/fastapi folder modules in the main package init file
You can reproduce the issue if you install the following pages: fastapi, frontegg and use your example code (in an isolated environment without flask)

Thanks

**Comment by staaam** [comment]
Similar issue here - we're using flask, but running `pip install frontegg` installs `aiohttp` with couple other dependent libs

**Comment by MoShitrit** [comment]
Same. I've just started working on implementing this library for my `FastAPI` app and as soon as I tried to start it up, I received an error related to missing `werkzeug` module:

```
  File "/Users/moshes/src/yow/backend-api/./app/main.py", line 10, in <module>
    from frontegg.fastapi import frontegg
  File "/Users/moshes/src/yow/backend-api/.venv/lib/python3.9/site-packages/frontegg/fastapi/__init__.py", line 1, in <module>
    from .frontegg import frontegg
  File "/Users/moshes/src/yow/backend-api/.venv/lib/python3.9/site-packages/frontegg/fastapi/frontegg.py", line 2, in <module>
    from frontegg.baseConfig.frontegg_proxy import FronteggProxy
  File "/Users/moshes/src/yow/backend-api/.venv/lib/python3.9/site-packages/frontegg/baseConfig/frontegg_proxy.py", line 9, in <module>
    from werkzeug.datastructures import Headers
ModuleNotFoundError: No module named 'werkzeug'
```

It appears that even with the `FastAPI` implementation, there's a tight coupling with `Flask` which is a bit of an overkill. I'd rather not have to install Flask related modules just to make FrontEgg's SDK work properly.

Thanks!
